### ISSUE TITLE
App not building on toolchain 46.0 f7

### ISSUE THREAD

**Issue by doomwastaken** [LTVA1/flizzer_tracker#3]
Greetings! I am from Flipper Devices team and would like to say thank you for submitting your app to the catalog. We are finalizing API prior to 1.0 release and currently your application cannot be built for latest toolchain. Currently we are testing 0.95.0-rc and app is not being built for that version.

We are currently working on automating the messages from our build server, so this one is manual :)

If you have any questions, just tag me

**Comment by LTVA1** [comment]
Okay, I haven't built it for a while... I need to update toolchain asap. I will use fbt because ufbt is like having API of closed-source core

**Comment by doomwastaken** [comment]
Yeah, whichever way is more comfortable for you. However you will need to bump app version and submit new pull request with version bump to the catalog, I will run and approve it as soon as possible. Thank you

**Comment by LTVA1** [comment]
Yeah I know... Can you give the exact error right here, though (if it like fails at compilation phase)? Because I will be able to compile only in late evening hopefully

**Comment by doomwastaken** [comment]
There is no rush to it, it is more of manual notification thing! Hopefully next week we will create an automated system for this type of thing. 

And obviously we can't wait for 1.0 API stabilization, so you do not have to make changes in order to comply with API

**Comment by LTVA1** [comment]
Well I want it to work on new releases anyway. I hooe it's an easy fix, however I don't know what exactly broke because you were refactoring NFC things iirc and my apps doesn't use them

**Comment by doomwastaken** [comment]
There is a warning from compiler, https://catalog.flipperzero.one/application/64f6668af19c44ead364c8f7/page
However currently logs/build details are not available due to a bug on a backend. Today we are planning to release new backend version and then I could provide more details. 

Part of an error available if you hover mouse on status

**Comment by LTVA1** [comment]
Okay you removed a bad thing from linker, thus it crashed... Now I seem to fix it, I use Unleashed so can't check rn, but it compiles on my PC just fine
